# Generated by Django 2.2 on 2019-04-19 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recensioni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(verbose_name='date published')),
                ('titolo', models.CharField(max_length=200)),
                ('descrizione', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('categoria', models.CharField(max_length=200)),
                ('bestplatform', models.BooleanField(default=False)),
                ('photo', models.ImageField(upload_to='platform')),
                ('recensioni', models.ManyToManyField(to='GigAdvisor.Recensioni')),
            ],
        ),
    ]
