# Generated by Django 2.2 on 2019-04-23 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GigAdvisor', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Platform',
        ),
        migrations.DeleteModel(
            name='Recensioni',
        ),
    ]
