# Generated by Django 2.2 on 2019-04-23 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('GigAdvisor', '0002_auto_20190423_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('categoria', models.CharField(max_length=200)),
                ('bestplatform', models.BooleanField(default=False)),
                ('photo', models.ImageField(upload_to='platform')),
            ],
        ),
        migrations.CreateModel(
            name='Recensioni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(verbose_name='date published')),
                ('titolo', models.CharField(max_length=200)),
                ('descrizione', models.CharField(max_length=2000)),
                ('platform', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GigAdvisor.Platform')),
            ],
        ),
    ]
