# Generated by Django 2.2 on 2019-07-01 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GigAdvisor', '0004_auto_20190628_1843'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recensioni',
            old_name='sicurezza',
            new_name='range1',
        ),
        migrations.AddField(
            model_name='recensioni',
            name='range2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recensioni',
            name='range3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recensioni',
            name='range4',
            field=models.IntegerField(default=0),
        ),
    ]
