# Generated by Django 2.2 on 2019-07-01 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GigAdvisor', '0005_auto_20190701_1954'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recensioni',
            old_name='range1',
            new_name='value1',
        ),
        migrations.RenameField(
            model_name='recensioni',
            old_name='range2',
            new_name='value2',
        ),
        migrations.RenameField(
            model_name='recensioni',
            old_name='range3',
            new_name='value3',
        ),
        migrations.RenameField(
            model_name='recensioni',
            old_name='range4',
            new_name='value4',
        ),
    ]
