# Generated by Django 2.2 on 2019-07-10 13:23

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GigAdvisor', '0010_auto_20190702_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=3),
        ),
    ]
