# Generated by Django 2.2 on 2019-07-31 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GigAdvisor', '0011_platform_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='recensioni',
            name='luogo',
            field=models.IntegerField(default=0),
        ),
    ]
