# Generated by Django 2.2 on 2019-07-31 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GigAdvisor', '0012_recensioni_luogo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recensioni',
            name='luogo',
            field=models.CharField(max_length=100),
        ),
    ]
