# Generated by Django 2.2 on 2019-08-01 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GigAdvisor', '0018_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
